[package]
name = "node-primitives"
version = "0.1.0"
authors = ["Stafi Protocol"]
edition = "2018"


[dependencies]
serde = { version = "1.0.102", features = [ "derive" ] }
sr-api = { git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
primitives = { package = "substrate-primitives", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
sr-primitives = { git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
parity-codec = { package = "parity-scale-codec", version = "1.0.6", default-features = false, features = ["derive"] }
rstd = { package = "sr-std", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }

[dev-dependencies]
substrate-serializer = { git = "https://github.com/stafiprotocol/stafi-blockchain" }
pretty_assertions = "0.6.1"

[features]
default = ["std"]
std = [
	"primitives/std",
	"parity-codec/std",
	"rstd/std",
	"sr-api/std",
	"sr-primitives/std",
]
