[package]
name = "stafi-crypto"
version = "0.1.0"
authors = ["Howie <technical@stafi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsodium-sys = { version = "0.2.4", optional = true}
bitcoin = { version = "^0.20", optional = true}
tiny-bip39 = { version = "0.6.2", optional = true}
rstd = { package = "sr-std", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
blake2-rfc = "0.2.18"
rust-crypto = "^0.2"

[dev-dependencies]
hex-literal = "0.2"

[features]
default = ["std"]
std = [
    "libsodium-sys",
    "bitcoin",
    "tiny-bip39", 
    "rstd/std"
]