[package]
name = "node-rpc"
version = "0.1.0"
authors = ["Stafi Protocol"]
edition = "2018"

[dependencies]
client = { package = "substrate-client", git = "https://github.com/stafiprotocol/stafi-blockchain" }
jsonrpc-core = "14.0.3"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
codec = { package = "parity-scale-codec", version = "1.0.6" }
hex = { version = "0.4.0" }
serde = { version = "1.0.102", features = [ "derive" ] }
node-primitives = { path = "../primitives" }
node-runtime = { path = "../runtime" }
sr-primitives = { git = "https://github.com/stafiprotocol/stafi-blockchain" }
paint-contracts-rpc = { git = "https://github.com/stafiprotocol/stafi-blockchain" }
paint-transaction-payment-rpc = { git = "https://github.com/stafiprotocol/stafi-blockchain" }
paint-system-rpc = { git = "https://github.com/stafiprotocol/stafi-blockchain" }
transaction_pool = { package = "substrate-transaction-pool", git = "https://github.com/stafiprotocol/stafi-blockchain" }
