[package]
name = "bridge-tezos"
version = "0.1.0"
authors = ["Howie <technical@stafi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
token-balances = { package = "stafi-crypto", path = "../stafi-crypto" }