[package]
name = "node-cli"
version = "0.2.2"
authors = ["Stafi Technologies <technical@stafi.io>"]
description = "Generic Stafi node implementation in Rust."
build = "build.rs"
edition = "2018"
default-run = "stafi"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[badges]
travis-ci = { repository = "stafiprotocol/stafi-node" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "stafiprotocol/stafi-node" }
is-it-maintained-open-issues = { repository = "stafiprotocol/stafi-node" }

[[bin]]
name = "stafi"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.3.1" }
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
futures = { version = "0.3.1", features = ["compat"] }
hex-literal = "0.2.1"
hex = "0.4.0"
jsonrpc-core = "14.2.0"
jsonrpc-pubsub = "14.2.0"
log = "0.4.8"
rand = "0.7.2"
structopt = { version = "0.3.8", optional = true }
tracing = "0.1.18"
parking_lot = "0.10.0"

# primitives
sp-authority-discovery = { version = "2.0.0-rc5",  git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sp-consensus-babe = { version = "0.8.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
grandpa-primitives = { version = "2.0.0-rc5", package = "sp-finality-grandpa", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sp-core = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sp-runtime = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sp-timestamp = { version = "2.0.0-rc5", default-features = false, git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sp-finality-tracker = { version = "2.0.0-rc5", default-features = false, git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sp-inherents = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sp-keyring = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sp-io = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sp-consensus = { version = "0.8.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sp-transaction-pool = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }

# client dependencies
sc-client-api = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sc-chain-spec = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sc-consensus = { version = "0.8.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sc-transaction-pool = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sc-network = { version = "0.8.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sc-consensus-babe = { version = "0.8.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
grandpa = { version = "0.8.0-rc5", package = "sc-finality-grandpa", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sc-client-db = { version = "0.8.0-rc5", default-features = false, git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sc-offchain = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sc-rpc = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sc-basic-authorship = { version = "0.8.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sc-service = { version = "0.8.0-rc5", default-features = false, git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sc-tracing = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sc-telemetry = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sc-authority-discovery = { version = "0.8.0-rc5",  git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }

# frame dependencies
pallet-indices = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
pallet-timestamp = { version = "2.0.0-rc5", default-features = false, git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
frame-system = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
pallet-balances = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
pallet-transaction-payment = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
frame-support = { version = "2.0.0-rc5", default-features = false, git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
pallet-im-online = { version = "2.0.0-rc5", default-features = false, git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
pallet-authority-discovery = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
pallet-staking = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
pallet-grandpa = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }

# node-specific dependencies
node-runtime = { version = "0.2.2", path = "../runtime" }
node-rpc = { version = "0.2.2", path = "../rpc" }
node-primitives = { version = "0.2.2", path = "../primitives" }
node-executor = { version = "0.2.2", path = "../executor" }

# CLI-specific dependencies
sc-cli = { version = "0.8.0-rc5", optional = true, git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
frame-benchmarking-cli = { version = "2.0.0-rc5", optional = true, git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
node-inspect = { version = "0.2.2", optional = true, path = "../inspect" }


[target.'cfg(target_arch="x86_64")'.dependencies]
node-executor = { version = "0.2.2", path = "../executor", features = [ "wasmtime" ] }
sc-cli = { version = "0.8.0-rc5", optional = true, git = 'https://github.com/stafiprotocol/stafi-blockchain.git', features = [ "wasmtime" ] }
sc-service = { version = "0.8.0-rc5", default-features = false, git = 'https://github.com/stafiprotocol/stafi-blockchain.git', features = [ "wasmtime" ] }
sp-trie = { version = "2.0.0-rc5", default-features = false, git = 'https://github.com/stafiprotocol/stafi-blockchain.git', features = ["memory-tracker"] }

[dev-dependencies]
sc-keystore = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sc-consensus = { version = "0.8.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sc-consensus-babe = { version = "0.8.0-rc5", features = ["test-helpers"], git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sc-consensus-epochs = { version = "0.8.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
sc-service-test = { version = "2.0.0-rc5", git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
futures = "0.3.4"
tempfile = "3.1.0"
assert_cmd = "1.0"
nix = "0.17"
serde_json = "1.0"
regex = "1"
platforms = "0.2.1"

[build-dependencies]
structopt = { version = "0.3.8", optional = true }
node-inspect = { version = "0.2.2", optional = true, path = "../inspect" }
frame-benchmarking-cli = { version = "2.0.0-rc5", optional = true, git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }
substrate-build-script-utils = { version = "2.0.0-rc5", optional = true, git = 'https://github.com/stafiprotocol/stafi-blockchain.git' }

[build-dependencies.sc-cli]
version = "0.8.0-rc5"
package = "sc-cli"
git = 'https://github.com/stafiprotocol/stafi-blockchain.git'
optional = true

[features]
default = [ "cli" ]
cli = [
	"node-executor/wasmi-errno",
	"node-inspect",
	"sc-cli",
	"frame-benchmarking-cli",
	"sc-service/db",
	"structopt",
	"substrate-build-script-utils",
]
runtime-benchmarks = [
	"node-runtime/runtime-benchmarks",
	"frame-benchmarking-cli",
]
