[package]
name = "node-executor"
version = "0.1.0"
authors = ["Stafi Protocol"]
edition = "2018"


[dependencies]
trie-root = "0.15.2"
codec = { package = "parity-scale-codec", version = "1.0.0" }
runtime_io = { package = "sr-io", git = "https://github.com/stafiprotocol/stafi-blockchain" }
state_machine = { package = "substrate-state-machine", git = "https://github.com/stafiprotocol/stafi-blockchain" }
substrate-executor = { git = "https://github.com/stafiprotocol/stafi-blockchain" }
primitives = { package = "substrate-primitives", git = "https://github.com/stafiprotocol/stafi-blockchain" }
trie = { package = "substrate-trie", git = "https://github.com/stafiprotocol/stafi-blockchain" }
node-primitives = { path = "../primitives" }
node-runtime = { path = "../runtime" }

[dev-dependencies]
test-client = { package = "substrate-test-client", git = "https://github.com/stafiprotocol/stafi-blockchain" }
sr-primitives = { git = "https://github.com/stafiprotocol/stafi-blockchain" }
runtime_support = { package = "paint-support", git = "https://github.com/stafiprotocol/stafi-blockchain" }
balances = { package = "paint-balances", git = "https://github.com/stafiprotocol/stafi-blockchain" }
transaction-payment = { package = "paint-transaction-payment", git = "https://github.com/stafiprotocol/stafi-blockchain" }
session = { package = "paint-session", git = "https://github.com/stafiprotocol/stafi-blockchain" }
system = { package = "paint-system", git = "https://github.com/stafiprotocol/stafi-blockchain" }
timestamp = { package = "paint-timestamp", git = "https://github.com/stafiprotocol/stafi-blockchain" }
treasury = { package = "paint-treasury", git = "https://github.com/stafiprotocol/stafi-blockchain" }
contracts = { package = "paint-contracts", git = "https://github.com/stafiprotocol/stafi-blockchain" }
grandpa = { package = "paint-grandpa", git = "https://github.com/stafiprotocol/stafi-blockchain" }
indices = { package = "paint-indices", git = "https://github.com/stafiprotocol/stafi-blockchain" }
wabt = "0.9.2"
criterion = "0.3.0"

[features]
wasmtime = [
    "substrate-executor/wasmtime",
]
wasmi-errno = [
	"substrate-executor/wasmi-errno",
]
stress-test = []

[[bench]]
name = "bench"
harness = false
