[package]
name = "fork-tree"
version = "2.0.0"
authors = ["Stafi Protocol <technical@stafi.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", features = ["derive"] }
